# Generated by Django 5.2.6 on 2025-09-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
