# Generated by Django 5.2.6 on 2025-09-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-number']},
        ),
    ]
