# Generated by Django 5.2.6 on 2025-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='title_EN',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='title_SK',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='number',
            field=models.IntegerField(default='0'),
        ),
    ]
