# Generated by Django 5.2.6 on 2025-09-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_photo_title_photo_title_en_photo_title_sk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_EN', models.CharField(max_length=100)),
                ('subtitle_EN', models.CharField(max_length=100)),
                ('title_SK', models.CharField(max_length=100)),
                ('subtitle_SK', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LatestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='0')),
                ('src', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='SliderHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default='0')),
                ('src', models.CharField(max_length=2083)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
