# Generated by Django 5.2.6 on 2025-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_calendar_latestphoto_sliderhome_alter_photo_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Calendar', 'verbose_name_plural': 'Home - Calendar'},
        ),
        migrations.AlterModelOptions(
            name='latestphoto',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Home - Latest photos'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-number'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Gallery - PHOTOS'},
        ),
        migrations.AlterModelOptions(
            name='sliderhome',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Home - Slider at the bottom'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='subtitle_EN',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='subtitle_SK',
            field=models.CharField(max_length=200),
        ),
    ]
