# Generated by Django 5.2.7 on 2025-11-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_calendar_options_alter_latestphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title_LT',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
