# Generated by Django 5.2.6 on 2026-09-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_photo_title_lt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestphoto',
            options={'ordering': ['-number'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Home - Latest photos'},
        ),
        migrations.AlterModelOptions(
            name='sliderhome',
            options={'ordering': ['-number'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Home - Slider at the bottom'},
        ),
    ]
