# Generated by Django 5.2.6 on 2026-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_latestphoto_options_alter_sliderhome_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='animal_type',
            field=models.CharField(choices=[('bird', 'Bird'), ('mammal', 'Mammal'), ('insect', 'Insect'), ('butterfly', 'Butterfly'), ('reptile', 'Reptile'), ('amphibian', 'Amphibian')], default='bird', max_length=20),
        ),
    ]
